routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Mail\Email;
 
Route::get('/email', function () {
 
   Mail::to('admin@luxodev.com')->send(new Email);
 
return view('emails.email');
 
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');

// Route::get('test', function () {
//     event(new App\Events\CustomerOrder());
//     return "Event has been sent!";
// });

Route::Group(['middleware'=>'App\Http\Middleware\AdminMiddleware'],function(){
    Route::resource('/currencies', 'CurrencyController');
    Route::resource('/currencies.detail_currencies', 'CurrencyDetailCurrencyController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/settings', 'SettingController');
    Route::get('/reports_view','ReportController@index2')->name('reports_view.index');
    Route::patch('/order_delivery/{order}','OrderController@update_delivery')->name('orders.update_delivery');
    Route::resource('/rates', 'RateController');
    Route::resource('/couriers', 'CourierController');
    Route::resource('/orders', 'OrderController');
    Route::resource('/users', 'UserController');
});

Route::Group(['middleware'=>'auth'],function(){
    Route::post('/logout','Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/rates', 'RateController@index')->name('rates.index');
    Route::get('/couriers', 'CourierController@index')->name('couriers.index');
    Route::get('/orders', 'OrderController@index')->name('orders.index');
});

resources/views/home.blade.php
@extends('layouts.app')
@section('title')
Dashboard
@endsection

@section('content')

<div class="col-md-6">
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Nilai Tukar Hari Ini</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Mata Uang</th>
                    <th>Rate</th>
                    <th style="width: 40px">Show</th>
                </tr>
                @foreach($currency as $c)
                <tr>
                    <td>{{$c->id}}</td>
                    <td>{{$c->name}}</td>
                    <td>{{$c->range}}</td>
                    <td>
                        <a href="{{route('rates.show',$c->id)}}">
                            <button class="btn btn-warning">
                                Show
                            </button>
                        </a>
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
<div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-aqua">
        <div class="inner">
            <h3>{{$order}}</h3>
            
            <p>Orders Waiting</p>
        </div>
        <div class="icon">
            <i class="ion ion-bag"></i>
        </div>
        <a href="/orders" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
</div>
<!-- ./col -->
<div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-yellow">
        <div class="inner">
            <h3>{{$customer}}</h3>
            <p>User Registrations</p>
        </div>
        <div class="icon">
            <i class="ion ion-person-add"></i>
        </div>
        <a href="/customers" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
</div>
@endsection