routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Mail\Email;
 
Route::get('/email', function () {
 
   Mail::to('admin@luxodev.com')->send(new Email);
 
return view('emails.email');
 
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');

// Route::get('test', function () {
//     event(new App\Events\CustomerOrder());
//     return "Event has been sent!";
// });

Route::Group(['middleware'=>'App\Http\Middleware\AdminMiddleware'],function(){
    Route::resource('/currencies', 'CurrencyController');
    Route::resource('/currencies.detail_currencies', 'CurrencyDetailCurrencyController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/settings', 'SettingController');
    Route::get('/reports_view','ReportController@index2')->name('reports_view.index');
    Route::patch('/order_delivery/{order}','OrderController@update_delivery')->name('orders.update_delivery');
    Route::resource('/rates', 'RateController');
    Route::resource('/couriers', 'CourierController');
    Route::resource('/orders', 'OrderController');
    Route::resource('/users', 'UserController');
});

Route::Group(['middleware'=>'auth'],function(){
    Route::post('/logout','Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/rates', 'RateController@index')->name('rates.index');
    Route::get('/couriers', 'CourierController@index')->name('couriers.index');
    Route::get('/orders', 'OrderController@index')->name('orders.index');
});

app/Currency.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    public function detail_currency(){
        return $this->hasMany('App\DetailCurrency','currency_id');
    }
    
    public function getRangeAttribute(){
        $today=Carbon::now()->startOfDay()->format('Y-m-d');
        $min=0;
        $max=0;
        foreach($this->detail_currency as $key => $dc){
            foreach($dc->currency_log as $cl){
                $date=new Carbon($cl->created_at);
                $date=$date->format('Y-m-d');
                if($date==$today){
                    if($key==0){
                        $min=$cl->price;
                        $max=$cl->price;
                    }else{
                        if($cl->price>$max){
                            $max=$cl->price;
                        }
                        if($cl->price<$min){
                            $min=$cl->price;
                        }
                    }
                }
            }
        }
        if($min==$max){
            return "IDR ".$min."";
        }else{
            return "IDR ".$min." - ".$max;
        }
    }

    public function getTotalStockAttribute(){
        $today=Carbon::now()->startOfDay()->format('Y-m-d');
        $total=0;
        foreach($this->detail_currency as $key => $dc){
            foreach($dc->currency_log as $cl){
                $date=new Carbon($cl->created_at);
                $date=$date->format('Y-m-d');
                if($date==$today){
                    $total+=$dc->nominal*$cl->stock;
                }
            }
        }
        return $total;
    }

    protected $appends =['range','total_stock'];
    protected $guarded =[];
}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use App\DetailCurrency;
use Illuminate\Http\Request;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $currency = Currency::query();
        
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $currency = $currency->where($key, 'like', '%'.$value.'%');
                }
            }
        }
        
        $currency = $currency->paginate(50);
        return view('currencies.index',compact('currency','filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $currency = new Currency;
        return view('currencies.create',compact('currency'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $currency = new Currency;
        $currency->fill($request->all());
        $currency->save();
        $request->session()->flash('toast', 'Mata Uang berhasil ditambahkan!');
        return redirect('/currencies');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function show(Currency $currency)
    {
        $detail_currency = DetailCurrency::query();
        $detail_currency = $detail_currency->where('currency_id', '=', $currency->id);
        $detail_currency = $detail_currency->paginate(5, ['*'], 'nominal');
        return view('currencies.show',compact('currency','detail_currency'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function edit(Currency $currency)
    {
        return view('currencies.create',compact('currency'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Currency $currency)
    {
        $currency->fill($request->all());
        $currency->save();
        $request->session()->flash('toast', 'Mata Uang berhasil diubah!');
        return redirect('/currencies');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        //
    }
}

resources/views/currencies/create.blade.php
@extends('layouts.app')

@section('title')
{{ $currency->exists ? 'Ubah' : 'Tambah' }} Mata Uang
@endsection
@section('content')

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <!-- /.box-header -->
        <!-- form start -->
      @if($currency->exists)
      {!! Form::model($currency, ['route' => ['currencies.update', $currency->id], 'method'=>'PATCH','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
      @else
      {!! Form::model($currency, ['route' => ['currencies.store'], 'method'=>'POST','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
      @endif
      <div class="box-body">
        <div class="row">
          <div class="form-group col-md-12">
            <label>Nama</label>
            {!! Form::text('name', $currency->name, ['class'=> 'form-control','required' => 'required']) !!}
          </div>
          <div class="form-group col-md-12">
            <label>Kode</label>
            {!! Form::text('code', $currency->code, ['class'=> 'form-control','required' => 'required']) !!}
          </div>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="col-md-12">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </div>
    </form>
  </div>
</div>
</div>
</section>
@endsection

resources/views/currencies/index.blade.php
@extends('layouts.app')

@section('title')
Manage Mata Uang
@endsection

@section('content')

<div class="row" style="margin-bottom:2vh;">
	<!-- Search User -->
	<form method="get" id="search-form">
		<div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[name]" placeholder="Nama" value="{{ !empty($filter['name']) ? $filter['name'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-primary btn-block">Cari</button>
		</div>
	</form>
</div>
<div class="box">
	<div class="box-header">
		<div class="row">
			<div class="col-md-3">
				<a href="{{ route('currencies.create')}}" class="btn btn-success btn-block">Tambah Mata Uang &nbsp;<span class="fa fa-plus-circle"></span></a>
			</div>
		</div>
	</div>
	
	<!-- /.box-header -->
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Kode</th>
					<th>Nama</th>
					<th>Show Detail</th>
				</tr>
			</thead>
			<tbody>
				@foreach($currency as $c)
				<tr>
					<td>{{$c->id}}</td>
					<td>{{$c->code}}</td>
					<td>{{$c->name}}</td>
					<td>
						<a href="{{route('currencies.show',$c->id)}}">
							<button class="btn btn-primary">
								Show
							</button>
						</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
		@php
		$filters = [];
		foreach ($filter as $key => $value) {
		$filters['filter['. $key .']'] = $value;
	}
	@endphp
	{{ $currency->appends($filters)->links() }}
</div>
</div>

@stop

resources/views/currencies/show.blade.php
@extends('layouts.app')

@section('title')
Manage Pecahan Mata Uang
@endsection

@section('content')
<div class="row">
    <section class="col-md-12">
        <div class="box">
            <div class="box-header">
            <div class="row">
            	<div class="col-md-12" >
                	<a href="{{route('currencies.edit',$currency->id)}}">
						<button class="btn btn-warning col-md-2 pull-right">
							Edit
						</button>
					</a>
            	</div>
           </div>
       </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-4">
                    <label>Mata Uang</label>
                    <p>{{$currency->name}}</p>
                </div>
            </div>
        </div>
    </section>
	<section class="col-md-12">
		<div class="box">
			
			<div class="box-header">
				<div class="row">
					<div class="col-md-4">
						<h3>Pecahan Mata Uang</h3>
					</div>
					<div class="col-md-4 pull-right">
						<a href="{{ route('currencies.detail_currencies.create',$currency->id)}}" class="btn btn-success btn-block">Tambah Pecahan Mata Uang &nbsp;<span class="fa fa-plus-circle"></span></a>
					</div>
				</div>
			</div>	
			<div class="box-body" style="height: 300px;overflow-y:visible" >
				<table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Nominal</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
						@foreach($detail_currency as $a)
						<tr> 
							<td>{{ $currency->name.' '.$a->nominal }}</td>
							<td>
								<a href="{{route('currencies.detail_currencies.edit',['currency'=>$currency->id,'detail_currency'=>$a->id])}}">
									<button class="btn btn-warning">
										Edit
									</button>
								</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				{{ $detail_currency->links() }}
			</div>
		</div>
	</section>
</div>
@stop