routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Mail\Email;
 
Route::get('/email', function () {
 
   Mail::to('admin@luxodev.com')->send(new Email);
 
return view('emails.email');
 
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');

// Route::get('test', function () {
//     event(new App\Events\CustomerOrder());
//     return "Event has been sent!";
// });

Route::Group(['middleware'=>'App\Http\Middleware\AdminMiddleware'],function(){
    Route::resource('/currencies', 'CurrencyController');
    Route::resource('/currencies.detail_currencies', 'CurrencyDetailCurrencyController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/settings', 'SettingController');
    Route::get('/reports_view','ReportController@index2')->name('reports_view.index');
    Route::patch('/order_delivery/{order}','OrderController@update_delivery')->name('orders.update_delivery');
    Route::resource('/rates', 'RateController');
    Route::resource('/couriers', 'CourierController');
    Route::resource('/orders', 'OrderController');
    Route::resource('/users', 'UserController');
});

Route::Group(['middleware'=>'auth'],function(){
    Route::post('/logout','Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/rates', 'RateController@index')->name('rates.index');
    Route::get('/couriers', 'CourierController@index')->name('couriers.index');
    Route::get('/orders', 'OrderController@index')->name('orders.index');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    public function getRoleNameAttribute(){
        if($this->role==1){
            return "Admin";
        }
        else if($this->role==2){
            return "Staff";
        }
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $appends = ['role_name'];
    protected $guarded = [];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = User::query();
        
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $user = $user->where($key, 'like', '%'.$value.'%');
                }
            }
        }
        
        $user = $user->paginate(50);
        return view('users.index',compact('user','filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User;
        return view('users.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
         ])->validate();

        $user = new User;
        $user->fill($request->all());
        $user->password = bcrypt($request->password);
        $user->save();
        $request->session()->flash('toast', 'User berhasil ditambahkan!');
        return redirect('/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.create',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        Validator::make($request->all(), [
            'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
            'password' => 'required|string|min:6|confirmed',
         ])->validate();

        $user->fill($request->all());    
        $user->password = bcrypt($request->password);
        $user->save();
        $request->session()->flash('toast', 'User berhasil diubah!');
        
        return redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, User $user)
    {
        try {
            $user->delete();
            $request->session()->flash('toast', 'User berhasil dihapus!');
        } catch(\Illuminate\Database\QueryException $ex){ 
            $request->session()->flash('toast', 'User gagal dihapus. ' . substr($ex->getMessage(),0,15));
        }
        
        return redirect('/users');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title')
{{ $user->exists ? 'Ubah' : 'Tambah' }} User
@endsection
@section('content')
@if($user->exists)
@section('actionbtn')
<a data-href="{{ route('users.destroy', ['user'=>$user->id]) }}" class="btn btn-danger destroy">Hapus User</a>
@endsection
@endif

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <!-- /.box-header -->
        <!-- form start -->
      @if($user->exists)
      {!! Form::model($user, ['route' => ['users.update', $user->id], 'method'=>'PATCH','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
      @else
      {!! Form::model($user, ['route' => ['users.store'], 'method'=>'POST','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
      @endif
      <div class="box-body">
        <div class="row">
          <div class="form-group col-md-12">
            <label>Nama</label>
            {!! Form::text('name', $user->name, ['class'=> 'form-control','required' => 'required']) !!}
          </div>
          <div class="form-group col-md-12">
            <label>Email</label>
            {!! Form::text('email', $user->email, ['class'=> 'form-control','required' => 'required']) !!}
            @if ($errors->has('email'))
              <div class="help-block text-red">
                {{ $errors->first('email') }}
              </div>
            @endif
          </div>
          <div class="form-group col-md-12">
            <label>Password</label>
            {!! Form::password('password', ['class'=> 'form-control','required' => 'required']) !!}
            @if ($errors->has('password'))
              <span class="help-block">
                <strong>{{ $errors->first('password') }}</strong>
              </span>
            @endif
          </div>
          <div class="form-group col-md-12">
            <label>Confirm Password</label>
            {!! Form::password('password_confirmation', ['class'=> 'form-control','required' => 'required']) !!}
          </div>
          <div class="form-group col-md-12">
            <label>Role</label>
            {!! Form::select('role', ['1' => 'Admin', '2' => 'Staff'], $user->role, ['placeholder'=>'Role','class'=> 'form-control select2','required' => 'required']) !!}
          </div>
        </div>
      </div>
      <!-- /.box-body -->
      <div class="box-footer">
        <div class="col-md-12">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </div>
    </form>
  </div>
</div>
</div>
</section>
@endsection
@include('layouts._deletebtn')

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title')
View User
@endsection

@section('content')

<div class="row" style="margin-bottom:2vh;">
	<!-- Search User -->
	<form method="get" id="search-form">
		<div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[name]" placeholder="Nama" value="{{ !empty($filter['name']) ? $filter['name'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
        </div>
        <div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[email]" placeholder="Email" value="{{ !empty($filter['email']) ? $filter['email'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-primary btn-block">Cari</button>
		</div>
	</form>
</div>
<div class="box">
	<div class="box-header">
		<div class="row">
			<div class="col-md-3">
				<a href="{{ route('users.create')}}" class="btn btn-success btn-block">Tambah User &nbsp;<span class="fa fa-plus-circle"></span></a>
			</div>
		</div>
	</div>
	<!-- /.box-header -->
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nama</th>
					<th>Email</th>
					<th>Role</th>
					<th>Show Detail</th>
				</tr>
			</thead>
			<tbody>
				@foreach($user as $u)
				<tr>
					<td>{{$u->id}}</td>
					<td>{{$u->name}}</td>
					<td>{{$u->email}}</td>
					<td>{{$u->role_name}}</td>
					<td>
						<a href="{{route('users.edit',$u->id)}}">
							<button class="btn btn-primary">
								Show
							</button>
						</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
		@php
		$filters = [];
		foreach ($filter as $key => $value) {
		$filters['filter['. $key .']'] = $value;
	}
	@endphp
	{{ $user->appends($filters)->links() }}
</div>
</div>
@stop