routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Mail\Email;
 
Route::get('/email', function () {
 
   Mail::to('admin@luxodev.com')->send(new Email);
 
return view('emails.email');
 
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
Route::post('/login','Auth\LoginController@login');

// Route::get('test', function () {
//     event(new App\Events\CustomerOrder());
//     return "Event has been sent!";
// });

Route::Group(['middleware'=>'App\Http\Middleware\AdminMiddleware'],function(){
    Route::resource('/currencies', 'CurrencyController');
    Route::resource('/currencies.detail_currencies', 'CurrencyDetailCurrencyController');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/settings', 'SettingController');
    Route::get('/reports_view','ReportController@index2')->name('reports_view.index');
    Route::patch('/order_delivery/{order}','OrderController@update_delivery')->name('orders.update_delivery');
    Route::resource('/rates', 'RateController');
    Route::resource('/couriers', 'CourierController');
    Route::resource('/orders', 'OrderController');
    Route::resource('/users', 'UserController');
});

Route::Group(['middleware'=>'auth'],function(){
    Route::post('/logout','Auth\LoginController@logout')->name('logout');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/rates', 'RateController@index')->name('rates.index');
    Route::get('/couriers', 'CourierController@index')->name('couriers.index');
    Route::get('/orders', 'OrderController@index')->name('orders.index');
});

app/Http/Controllers/CurrencyDetailCurrencyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use App\Currency;
use App\DetailCurrency;
use App\CurrencyLog;
use Illuminate\Http\Request;

class CurrencyDetailCurrencyController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        //
    }
    
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create(Currency $currency)
    {
        $detail_currency = new DetailCurrency;
        return view('currency_detail_currencies.create',compact('detail_currency','currency'));
    }
    
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request, Currency $currency)
    {
        $a = $currency->id;
        Validator::make($request->all(), [
            'nominal' => Rule::unique('detail_currencies')->where(function ($query) use ($a) {
                return $query->where('currency_id', $a);
            })
         ])->validate();
        $detail_currency = new DetailCurrency;
        $detail_currency->fill($request->all());
        $detail_currency->currency_id=$currency->id;
        $detail_currency->save();
        $currency_log = new CurrencyLog;
        $currency_log->detail_currency_id = $detail_currency->id;
        $currency_log->stock = 0;
        $currency_log->price = 0;
        $currency_log->save();
        $request->session()->flash('toast','Pecahan Mata Uang berhasil ditambahkan!');
        return redirect('/currencies/'.$currency->id);
    }
    
    /**
    * Display the specified resource.
    *
    * @param  \App\DetailCurrency  $detailCurrency
    * @return \Illuminate\Http\Response
    */
    public function show(DetailCurrency $detail_currency)
    {
        //
    }
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\DetailCurrency  $detailCurrency
    * @return \Illuminate\Http\Response
    */
    public function edit(Currency $currency, DetailCurrency $detail_currency)
    {
        return view('currency_detail_currencies.create',compact('detail_currency','currency'));
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\DetailCurrency  $detailCurrency
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Currency $currency, DetailCurrency $detail_currency)
    {
        $detail_currency->fill($request->all());
        $detail_currency->currency_id=$currency->id;
        $detail_currency->save();
        $request->session()->flash('toast','Pecahan Mata Uang berhasil diubah!');
        return redirect('/currencies/'.$currency->id);
    }
    
    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\DetailCurrency  $detailCurrency
    * @return \Illuminate\Http\Response
    */
    public function destroy(Request $request, Currency $currency, DetailCurrency $detail_currency)
    {
        
        try{
            $currency_log = CurrencyLog::where('detail_currency_id','=',$detail_currency->id)->first();
            $currency_log->delete();
            $detail_currency->delete();
            $request->session()->flash('toast','Pecahan Mata Uang berhasil dihapus');
        }
        catch(\Illuminate\Database\QueryException $ex){
            $request->session()->flash('fail','Pecahan Mata Uang gagal dihapus '.substr($ex->getMessage(),0,15));
        };
        return redirect('/currencies/'.$currency->id);
    }
}

resources/views/currency_detail_currencies/create.blade.php
@extends('layouts.app')

@section('title')
{{ $detail_currency->exists ? 'Ubah' : 'Tambah' }} Pecahan Mata Uang
@endsection
@section('content')
@if($detail_currency->exists)
@section('actionbtn')
<a data-href="{{ route('currencies.detail_currencies.destroy', ['currency'=>$currency->id,'detail_currency'=>$detail_currency->id]) }}" class="btn btn-danger destroy">Hapus Pecahan Mata Uang</a>
@endsection
@endif

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <!-- /.box-header -->
        <!-- form start -->
        @if($detail_currency->exists)
        {!! Form::model($detail_currency, ['route' => ['currencies.detail_currencies.update', 'currency'=>$currency->id, 'detail_currency'=>$detail_currency->id], 'method'=>'PATCH','role' => 'form']) !!}
        @else
        {!! Form::model($detail_currency, ['route' => ['currencies.detail_currencies.store',$currency->id], 'method'=>'POST', 'role' => 'form']) !!}
        @endif
        <div class="box-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label>Nominal</label>
              {!! Form::number('nominal',$detail_currency->nominal,['class'=> 'form-control','require'=>'required']) !!}
              @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                  @foreach ($errors->all() as $error)
                      {{ $error }}
                  @endforeach
                </ul>
              </div>
              @endif
            </div>
          </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
</section>
@endsection
@include('layouts._deletebtn')